// Generated by `wit-bindgen` 0.44.0. DO NOT EDIT!
#ifndef __BINDINGS_APP_H
#define __BINDINGS_APP_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct app_string_t {
  uint8_t*ptr;
  size_t len;
} app_string_t;

typedef struct {
  app_string_t *ptr;
  size_t len;
} app_list_string_t;

// Exported Functions from `my:app/iface@0.1.0`
uint32_t exports_my_app_iface_start(app_list_string_t *args);

// Helper Functions

void app_list_string_free(app_list_string_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void app_string_set(app_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void app_string_dup(app_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void app_string_free(app_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
