// Generated by `wit-bindgen` 0.44.0. DO NOT EDIT!
#include "app.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `my:app/iface@0.1.0`


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void app_list_string_free(app_list_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    app_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      app_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void app_string_set(app_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void app_string_dup(app_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void app_string_free(app_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("my:app/iface@0.1.0#start")))
int32_t __wasm_export_exports_my_app_iface_start(uint8_t * arg, size_t arg0) {
  app_list_string_t arg1 = (app_list_string_t) { (app_string_t*)(arg), (arg0) };
  uint32_t ret = exports_my_app_iface_start(&arg1);
  return (int32_t) (ret);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_app(void);
__attribute__((used))
void __component_type_object_force_link_app_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_app();
}
