import { Emlite } from "emlite";
import { WASIShim } from "@bytecodealliance/preview2-shim/instantiation";
// generated by jco
import { instantiate as initApp } from "../bin/app/main.js";

async function main() {
  const getAppCore = (p) =>
    WebAssembly.compileStreaming(
      fetch(new URL(`../bin/app/${p}`, import.meta.url))
    );

  const wasiShim = new WASIShim({});
  const wasi = wasiShim.getImportObject();

  const emlite = new Emlite();
  const app = await initApp(getAppCore, {
    ...wasi,
    "emlite:env/host": emlite.componentHost,
  });
  emlite.bindComponent(app);

  app.run.run();
}

await main();